
package nyproje;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class AnaEkran extends javax.swing.JFrame {
    private static Distributor distributor = new Distributor(); //distributor ogemizi olusturuyoruz.

    public static Distributor getDistributor() {
        return distributor; //diger ekranlarda distributor uzerinde islem yapacagiz. getter lazim.
    }

    public static void setDistributor(Distributor distributor) {
        AnaEkran.distributor = distributor;
    }

    public AnaEkran() {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); // Ana ekranin kapatilmasini onluyoruz.
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                // Kapatma islemini kontrol ediyoruz.
                int result = JOptionPane.showConfirmDialog(AnaEkran.this, "Are you sure you want to exit? Don't forget to save?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    System.exit(0); // Cikisi onayladiysa cik.
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Journalolusturma = new javax.swing.JButton();
        createSubscriber = new javax.swing.JToggleButton();
        searchjournalbutton = new javax.swing.JButton();
        searchjournaltextfield = new javax.swing.JTextField();
        searchsubscriberbutton = new javax.swing.JButton();
        searchsubscribertextfield = new javax.swing.JTextField();
        addsubscriptionbutton = new javax.swing.JButton();
        acceptpaymentbutton = new javax.swing.JButton();
        paymentjournalissntextfield = new javax.swing.JTextField();
        paymentsubscribernametextfield = new javax.swing.JTextField();
        amounttextfield = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        loadstate = new javax.swing.JButton();
        savestate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ExpireMonth = new javax.swing.JTextField();
        reportbutton = new javax.swing.JButton();
        ExpireYear = new javax.swing.JTextField();
        Year2 = new javax.swing.JTextField();
        Year1 = new javax.swing.JTextField();
        expireddates = new javax.swing.JLabel();
        annualpayments = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        listallsendingordersbutton = new javax.swing.JButton();
        ListSendingOrdersParticularJournal = new javax.swing.JButton();
        ListIncompletePaymentsButton = new javax.swing.JButton();
        ListSubscriptionsByNameButton = new javax.swing.JButton();
        ListSubscriptionsByJournal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Journalolusturma.setBackground(new java.awt.Color(255, 255, 51));
        Journalolusturma.setText("Add Journal");
        Journalolusturma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JournalolusturmaActionPerformed(evt);
            }
        });

        createSubscriber.setBackground(new java.awt.Color(255, 255, 51));
        createSubscriber.setText("Add Subscriber");
        createSubscriber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSubscriberActionPerformed(evt);
            }
        });

        searchjournalbutton.setBackground(new java.awt.Color(255, 255, 102));
        searchjournalbutton.setText("Search Journal");
        searchjournalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjournalbuttonActionPerformed(evt);
            }
        });

        searchjournaltextfield.setForeground(new java.awt.Color(51, 255, 204));
        searchjournaltextfield.setText("Enter Journal ISSN");
        searchjournaltextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchjournaltextfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchjournaltextfieldFocusLost(evt);
            }
        });
        searchjournaltextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjournaltextfieldActionPerformed(evt);
            }
        });

        searchsubscriberbutton.setBackground(new java.awt.Color(255, 255, 102));
        searchsubscriberbutton.setText("Search Subscriber");
        searchsubscriberbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchsubscriberbuttonActionPerformed(evt);
            }
        });

        searchsubscribertextfield.setForeground(new java.awt.Color(51, 255, 204));
        searchsubscribertextfield.setText("Enter Subscriber Name");
        searchsubscribertextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchsubscribertextfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchsubscribertextfieldFocusLost(evt);
            }
        });
        searchsubscribertextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchsubscribertextfieldActionPerformed(evt);
            }
        });

        addsubscriptionbutton.setBackground(new java.awt.Color(255, 255, 102));
        addsubscriptionbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addsubscriptionbutton.setText("Add Subscription");
        addsubscriptionbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsubscriptionbuttonActionPerformed(evt);
            }
        });

        acceptpaymentbutton.setBackground(new java.awt.Color(255, 255, 102));
        acceptpaymentbutton.setText("Accept Payment for Subscription");
        acceptpaymentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptpaymentbuttonActionPerformed(evt);
            }
        });

        paymentjournalissntextfield.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        paymentjournalissntextfield.setForeground(new java.awt.Color(102, 255, 204));
        paymentjournalissntextfield.setText("Enter Journal ISSN");
        paymentjournalissntextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentjournalissntextfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paymentjournalissntextfieldFocusLost(evt);
            }
        });
        paymentjournalissntextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentjournalissntextfieldActionPerformed(evt);
            }
        });

        paymentsubscribernametextfield.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        paymentsubscribernametextfield.setForeground(new java.awt.Color(102, 255, 204));
        paymentsubscribernametextfield.setText("Enter Subscriber Name");
        paymentsubscribernametextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentsubscribernametextfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paymentsubscribernametextfieldFocusLost(evt);
            }
        });

        amounttextfield.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        amounttextfield.setForeground(new java.awt.Color(102, 255, 204));
        amounttextfield.setText("Amount");
        amounttextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amounttextfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                amounttextfieldFocusLost(evt);
            }
        });
        amounttextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amounttextfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchjournaltextfield)
                            .addComponent(searchjournalbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Journalolusturma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createSubscriber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchsubscriberbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchsubscribertextfield))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(addsubscriptionbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(paymentjournalissntextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(paymentsubscribernametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(amounttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(acceptpaymentbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentjournalissntextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentsubscribernametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amounttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acceptpaymentbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addsubscriptionbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchjournaltextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchsubscribertextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchjournalbutton)
                    .addComponent(searchsubscriberbutton))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Journalolusturma)
                    .addComponent(createSubscriber))
                .addGap(30, 30, 30))
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        loadstate.setBackground(new java.awt.Color(255, 255, 51));
        loadstate.setText("LoadState");
        loadstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadstateActionPerformed(evt);
            }
        });

        savestate.setBackground(new java.awt.Color(255, 255, 51));
        savestate.setText("SaveState");
        savestate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savestateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadstate)
                    .addComponent(savestate))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(loadstate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(savestate)
                .addGap(21, 21, 21))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ExpireMonth.setForeground(new java.awt.Color(102, 255, 204));
        ExpireMonth.setText("Expire Month");
        ExpireMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ExpireMonthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ExpireMonthFocusLost(evt);
            }
        });

        reportbutton.setBackground(new java.awt.Color(255, 102, 102));
        reportbutton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        reportbutton.setForeground(new java.awt.Color(102, 102, 102));
        reportbutton.setText("Report");
        reportbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbuttonActionPerformed(evt);
            }
        });

        ExpireYear.setForeground(new java.awt.Color(102, 255, 204));
        ExpireYear.setText("Expire Year");
        ExpireYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ExpireYearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ExpireYearFocusLost(evt);
            }
        });

        Year2.setForeground(new java.awt.Color(102, 255, 204));
        Year2.setText("Year 2");
        Year2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Year2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Year2FocusLost(evt);
            }
        });

        Year1.setForeground(new java.awt.Color(102, 255, 204));
        Year1.setText("Year 1");
        Year1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Year1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Year1FocusLost(evt);
            }
        });

        expireddates.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        expireddates.setText("Subscriptions that will be expired after a given date.");

        annualpayments.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        annualpayments.setText("Annual payments in a given year range.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ExpireMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(ExpireYear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Year1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Year2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(reportbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(expireddates, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(annualpayments)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expireddates, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annualpayments))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpireMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpireYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(reportbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        listallsendingordersbutton.setBackground(new java.awt.Color(255, 255, 102));
        listallsendingordersbutton.setText("List All Sending Orders");
        listallsendingordersbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listallsendingordersbuttonActionPerformed(evt);
            }
        });

        ListSendingOrdersParticularJournal.setBackground(new java.awt.Color(255, 255, 51));
        ListSendingOrdersParticularJournal.setText("List Sending Orders For Particular Journal");
        ListSendingOrdersParticularJournal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListSendingOrdersParticularJournalActionPerformed(evt);
            }
        });

        ListIncompletePaymentsButton.setBackground(new java.awt.Color(255, 255, 102));
        ListIncompletePaymentsButton.setText("List Incomplete Payments");
        ListIncompletePaymentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListIncompletePaymentsButtonActionPerformed(evt);
            }
        });

        ListSubscriptionsByNameButton.setBackground(new java.awt.Color(255, 255, 102));
        ListSubscriptionsByNameButton.setText("List All Subscriptions of a Subscriber");
        ListSubscriptionsByNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListSubscriptionsByNameButtonActionPerformed(evt);
            }
        });

        ListSubscriptionsByJournal.setBackground(new java.awt.Color(255, 255, 102));
        ListSubscriptionsByJournal.setText("List All Subscriptions of a Journal");
        ListSubscriptionsByJournal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListSubscriptionsByJournalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listallsendingordersbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListSendingOrdersParticularJournal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListIncompletePaymentsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListSubscriptionsByNameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListSubscriptionsByJournal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(listallsendingordersbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListSendingOrdersParticularJournal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListIncompletePaymentsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListSubscriptionsByNameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListSubscriptionsByJournal)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Year1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Year1FocusLost
        if (Year1.getText().isEmpty()) {
            Year1.setText("Year 1");
            Year1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_Year1FocusLost

    private void Year1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Year1FocusGained
        Year1.setText("");
        Year1.setForeground(Color.BLACK);
    }//GEN-LAST:event_Year1FocusGained

    private void Year2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Year2FocusLost
        if (Year2.getText().isEmpty()) {
            Year2.setText("Year 2");
            Year2.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_Year2FocusLost

    private void Year2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Year2FocusGained
        Year2.setText("");
        Year2.setForeground(Color.BLACK);
    }//GEN-LAST:event_Year2FocusGained

    private void ExpireYearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ExpireYearFocusLost
        if (ExpireYear.getText().isEmpty()) {
            ExpireYear.setText("Expire Year");
            ExpireYear.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_ExpireYearFocusLost

    private void ExpireYearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ExpireYearFocusGained
        ExpireYear.setText("");
        ExpireYear.setForeground(Color.BLACK);
    }//GEN-LAST:event_ExpireYearFocusGained

    private void reportbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbuttonActionPerformed
        try{
            distributor.report(Integer.parseInt(ExpireMonth.getText()), Integer.parseInt(ExpireYear.getText()), Integer.parseInt(Year1.getText()), Integer.parseInt(Year2.getText()));
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Gecerli sayi degerleri giriniz.", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_reportbuttonActionPerformed

    private void ExpireMonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ExpireMonthFocusLost
        if (ExpireMonth.getText().isEmpty()) {
            ExpireMonth.setText("Expire Month");
            ExpireMonth.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_ExpireMonthFocusLost

    private void ExpireMonthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ExpireMonthFocusGained
        ExpireMonth.setText("");
        ExpireMonth.setForeground(Color.BLACK);
    }//GEN-LAST:event_ExpireMonthFocusGained

    private void savestateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savestateActionPerformed
        if (this.distributor.saveState("distributors.ser")) {
            JOptionPane.showMessageDialog(this, "Basariyla kaydedildi!", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Kaydetme sirasinda hata oldu!", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_savestateActionPerformed

    private void loadstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadstateActionPerformed
        if (this.distributor.loadState("distributors.ser")) {
            JOptionPane.showMessageDialog(this, "Eski Kayit Basariyla Yuklendi.!", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Yukleme sirasinda hata oldu!", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loadstateActionPerformed

    private void paymentsubscribernametextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentsubscribernametextfieldFocusLost
        if (paymentsubscribernametextfield.getText().isEmpty()) {
            paymentsubscribernametextfield.setText("Enter Subscriber Name");
            paymentsubscribernametextfield.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_paymentsubscribernametextfieldFocusLost

    private void paymentsubscribernametextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentsubscribernametextfieldFocusGained
        paymentsubscribernametextfield.setText("");
        paymentsubscribernametextfield.setForeground(Color.BLACK);
    }//GEN-LAST:event_paymentsubscribernametextfieldFocusGained

    private void paymentjournalissntextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentjournalissntextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentjournalissntextfieldActionPerformed

    private void paymentjournalissntextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentjournalissntextfieldFocusLost
        if (paymentjournalissntextfield.getText().isEmpty()) {
            paymentjournalissntextfield.setText("Enter Journal ISSN");
            paymentjournalissntextfield.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_paymentjournalissntextfieldFocusLost

    private void paymentjournalissntextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentjournalissntextfieldFocusGained
        paymentjournalissntextfield.setText("");
        paymentjournalissntextfield.setForeground(Color.BLACK);
    }//GEN-LAST:event_paymentjournalissntextfieldFocusGained

    private void addsubscriptionbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsubscriptionbuttonActionPerformed
        AddSubscriptionEkran addsubscriptionekran = new AddSubscriptionEkran();
        addsubscriptionekran.setVisible(true);
    }//GEN-LAST:event_addsubscriptionbuttonActionPerformed

    private void searchsubscribertextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchsubscribertextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchsubscribertextfieldActionPerformed

    private void searchsubscribertextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchsubscribertextfieldFocusLost
        if (searchsubscribertextfield.getText().isEmpty()) {
            searchsubscribertextfield.setText("Enter Subscriber Name");
            searchsubscribertextfield.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_searchsubscribertextfieldFocusLost

    private void searchsubscribertextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchsubscribertextfieldFocusGained
        searchsubscribertextfield.setText("");
        searchsubscribertextfield.setForeground(Color.BLACK);
    }//GEN-LAST:event_searchsubscribertextfieldFocusGained

    private void searchsubscriberbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchsubscriberbuttonActionPerformed
        String name = searchsubscribertextfield.getText();
        if(name.equals("Enter Subscriber Name")){
            JOptionPane.showMessageDialog(this,"Enter a Subscriber Name","Hata", JOptionPane.ERROR_MESSAGE); //once bir subscriber ismi girmeli.
        }
        else if(distributor.searchSubscriber(name) == null){
            JOptionPane.showMessageDialog(this,"Subscriber " + name + " can not found.","Hata", JOptionPane.ERROR_MESSAGE); //subscriberi bulamadiysa
        }
        else{
            JOptionPane.showMessageDialog(this,"Subscriber "+ name + " found.");
        }
    }//GEN-LAST:event_searchsubscriberbuttonActionPerformed

    private void searchjournaltextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjournaltextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchjournaltextfieldActionPerformed

    private void searchjournaltextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchjournaltextfieldFocusLost
        if (searchjournaltextfield.getText().isEmpty()) {
            searchjournaltextfield.setText("Enter Journal ISSN");
            searchjournaltextfield.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_searchjournaltextfieldFocusLost

    private void searchjournaltextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchjournaltextfieldFocusGained

        searchjournaltextfield.setText("");
        searchjournaltextfield.setForeground(Color.BLACK);
    }//GEN-LAST:event_searchjournaltextfieldFocusGained

    private void searchjournalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjournalbuttonActionPerformed
        String issn = searchjournaltextfield.getText();
        if(issn.equals("Enter Journal ISSN")){//once bir issn girmeli.
            JOptionPane.showMessageDialog(this,"Enter a issn number.","Hata", JOptionPane.ERROR_MESSAGE);
        }
        else if(distributor.searchJournal(issn) == null){ //bulamadiysa.
            JOptionPane.showMessageDialog(this,"Journal can not found.","Hata", JOptionPane.ERROR_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this,"Journal with "+ issn + " issn found.");
        }
    }//GEN-LAST:event_searchjournalbuttonActionPerformed

    private void createSubscriberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSubscriberActionPerformed

        SubscriberOlusturEkrani subscriberolusturekrani = new SubscriberOlusturEkrani();

        subscriberolusturekrani.setVisible(true);
    }//GEN-LAST:event_createSubscriberActionPerformed

    private void JournalolusturmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JournalolusturmaActionPerformed
        JournalOlusturEkran journalolusturekran = new JournalOlusturEkran();
        journalolusturekran.setVisible(true);
    }//GEN-LAST:event_JournalolusturmaActionPerformed

    private void acceptpaymentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptpaymentbuttonActionPerformed
        String issn = paymentjournalissntextfield.getText();
        String subscriberName = paymentsubscribernametextfield.getText();
        int flag = 0;
        try{
            double amount = Double.parseDouble(amounttextfield.getText());
            Journal journal = distributor.searchJournal(issn);
            Subscriber subscriber = distributor.searchSubscriber(subscriberName);
            if(journal != null && subscriber != null){
                for(Subscription subscription:journal.getSubscriptions()){
                    if(subscription.getSubscriber().equals(subscriber)){
                        subscription.acceptPayment(amount);
                        flag = 1;
                        JOptionPane.showMessageDialog(this,subscriber.getName()+" isimli abone icin Para kabulu basarili! ");
                    }
                }
                if(flag == 0){
                    JOptionPane.showMessageDialog(this,"Para kabulu BASARISIZ!","Hata", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Para kabulu BASARISIZ!","Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Enter a valid value","Hata", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_acceptpaymentbuttonActionPerformed

    private void amounttextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amounttextfieldActionPerformed
        
    }//GEN-LAST:event_amounttextfieldActionPerformed

    private void amounttextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amounttextfieldFocusGained
        amounttextfield.setText("");
        amounttextfield.setForeground(Color.BLACK);
    }//GEN-LAST:event_amounttextfieldFocusGained

    private void amounttextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amounttextfieldFocusLost
         if (amounttextfield.getText().isEmpty()) {
            amounttextfield.setText("Amount");
            amounttextfield.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_amounttextfieldFocusLost

    private void listallsendingordersbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listallsendingordersbuttonActionPerformed
       ListAllSendingOrdersEkrani listallsendingordersekrani = new ListAllSendingOrdersEkrani();

        listallsendingordersekrani.setVisible(true);
    }//GEN-LAST:event_listallsendingordersbuttonActionPerformed

    private void ListSendingOrdersParticularJournalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListSendingOrdersParticularJournalActionPerformed
        ListSendingOrdersForParticularJournalEkrani listsendingordersforparticularjournalekrani = new ListSendingOrdersForParticularJournalEkrani();

        listsendingordersforparticularjournalekrani.setVisible(true);
    }//GEN-LAST:event_ListSendingOrdersParticularJournalActionPerformed

    private void ListIncompletePaymentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListIncompletePaymentsButtonActionPerformed
        ListIncompletePaymentsEkrani listincompletepaymentsekrani = new ListIncompletePaymentsEkrani();
        listincompletepaymentsekrani.setVisible(true);
    }//GEN-LAST:event_ListIncompletePaymentsButtonActionPerformed

    private void ListSubscriptionsByNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListSubscriptionsByNameButtonActionPerformed
        ListSubscriptionsbyNameEkrani listsubscriptionsbynameekrani = new ListSubscriptionsbyNameEkrani();
        listsubscriptionsbynameekrani.setVisible(true);
    }//GEN-LAST:event_ListSubscriptionsByNameButtonActionPerformed

    private void ListSubscriptionsByJournalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListSubscriptionsByJournalActionPerformed
        ListSubscriptionsbyISSN listsubscriptionsbyissn = new ListSubscriptionsbyISSN();
        listsubscriptionsbyissn.setVisible(true);
    }//GEN-LAST:event_ListSubscriptionsByJournalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ExpireMonth;
    private javax.swing.JTextField ExpireYear;
    private javax.swing.JButton Journalolusturma;
    private javax.swing.JButton ListIncompletePaymentsButton;
    private javax.swing.JButton ListSendingOrdersParticularJournal;
    private javax.swing.JButton ListSubscriptionsByJournal;
    private javax.swing.JButton ListSubscriptionsByNameButton;
    private javax.swing.JTextField Year1;
    private javax.swing.JTextField Year2;
    private javax.swing.JButton acceptpaymentbutton;
    private javax.swing.JButton addsubscriptionbutton;
    private javax.swing.JTextField amounttextfield;
    private javax.swing.JLabel annualpayments;
    private javax.swing.JToggleButton createSubscriber;
    private javax.swing.JLabel expireddates;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton listallsendingordersbutton;
    private javax.swing.JButton loadstate;
    private javax.swing.JTextField paymentjournalissntextfield;
    private javax.swing.JTextField paymentsubscribernametextfield;
    private javax.swing.JButton reportbutton;
    private javax.swing.JButton savestate;
    private javax.swing.JButton searchjournalbutton;
    private javax.swing.JTextField searchjournaltextfield;
    private javax.swing.JButton searchsubscriberbutton;
    private javax.swing.JTextField searchsubscribertextfield;
    // End of variables declaration//GEN-END:variables
}
