
package nyproje;

import javax.swing.JOptionPane;

public class CorporationOlusturEkrani extends javax.swing.JFrame {

    /**
     * Creates new form Corporationolustur
     */
    public CorporationOlusturEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        subscribe = new javax.swing.JButton();
        corporationname = new javax.swing.JLabel();
        corporation_name_alani = new javax.swing.JTextField();
        adress = new javax.swing.JLabel();
        adress_alani = new javax.swing.JTextField();
        bankcode = new javax.swing.JLabel();
        bank_code_alani = new javax.swing.JTextField();
        bankname = new javax.swing.JLabel();
        bank_name_alani = new javax.swing.JTextField();
        issueday = new javax.swing.JLabel();
        issue_month_alani = new javax.swing.JTextField();
        issue_year_alani = new javax.swing.JTextField();
        issuemonth = new javax.swing.JLabel();
        issueyear = new javax.swing.JLabel();
        issue_day_alani = new javax.swing.JTextField();
        accountnumber = new javax.swing.JLabel();
        account_number_alani = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Corporation");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        subscribe.setBackground(new java.awt.Color(255, 255, 51));
        subscribe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subscribe.setText("subscribe");
        subscribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscribeActionPerformed(evt);
            }
        });

        corporationname.setText("Corporationname");

        adress.setText("Adress");

        adress_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adress_alaniActionPerformed(evt);
            }
        });

        bankcode.setText("Bankcode");

        bankname.setText("BankName");

        issueday.setText("issue day");

        issuemonth.setText("issue month");

        issueyear.setText("issue year");

        accountnumber.setText("AccountNumber");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(corporationname))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(issueday)
                                .addComponent(bankname)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adress)
                            .addComponent(bankcode)))
                    .addComponent(accountnumber, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subscribe, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(corporation_name_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addComponent(adress_alani)
                        .addComponent(bank_code_alani)
                        .addComponent(bank_name_alani))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(issue_month_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issuemonth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issue_year_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issueyear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issue_day_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(account_number_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(441, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corporation_name_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(corporationname))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adress)
                    .addComponent(adress_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankcode)
                    .addComponent(bank_code_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankname)
                    .addComponent(bank_name_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueday)
                    .addComponent(issue_month_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issue_year_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuemonth)
                    .addComponent(issueyear)
                    .addComponent(issue_day_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountnumber)
                    .addComponent(account_number_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(subscribe, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subscribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscribeActionPerformed
        String isim = corporation_name_alani.getText();
        String adress = adress_alani.getText();
        String bankname = bank_name_alani.getText();
        try{
            int bankCode = Integer.parseInt(bank_code_alani.getText());
            int issueDay = Integer.parseInt(issue_day_alani.getText());
            int issueMonth = Integer.parseInt(issue_month_alani.getText());
            int issueYear = Integer.parseInt(issue_year_alani.getText());
            int accountNumber = Integer.parseInt(account_number_alani.getText());
            Distributor distributor = AnaEkran.getDistributor();
            Subscriber corporation = new Corporation(isim, adress, bankCode, bankname, issueDay, issueMonth, issueYear, accountNumber);
            if(distributor.addSubscriber(corporation)){
                JOptionPane.showMessageDialog(this,"Subscriber added succesfully:" + isim + ", " +  adress);
                setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(this,"This subscriber already exists.");
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Enter a valid value.", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_subscribeActionPerformed

    private void adress_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adress_alaniActionPerformed
        // TODO add
    }//GEN-LAST:event_adress_alaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CorporationOlusturEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CorporationOlusturEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CorporationOlusturEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CorporationOlusturEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CorporationOlusturEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account_number_alani;
    private javax.swing.JLabel accountnumber;
    private javax.swing.JLabel adress;
    private javax.swing.JTextField adress_alani;
    private javax.swing.JTextField bank_code_alani;
    private javax.swing.JTextField bank_name_alani;
    private javax.swing.JLabel bankcode;
    private javax.swing.JLabel bankname;
    private javax.swing.JTextField corporation_name_alani;
    private javax.swing.JLabel corporationname;
    private javax.swing.JTextField issue_day_alani;
    private javax.swing.JTextField issue_month_alani;
    private javax.swing.JTextField issue_year_alani;
    private javax.swing.JLabel issueday;
    private javax.swing.JLabel issuemonth;
    private javax.swing.JLabel issueyear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton subscribe;
    // End of variables declaration//GEN-END:variables
}
