
package nyproje;

import java.time.LocalDate;

public class ListIncompletePaymentsEkrani extends javax.swing.JFrame {

    /**
     * Creates new form ListIncompletePaymentsEkrani
     */
    public ListIncompletePaymentsEkrani() {
        initComponents();
        Distributor distributor  = AnaEkran.getDistributor();
        OutputArea.setText("");
        LocalDate currentDate = LocalDate.now(); //local zamanlari cekiyoruz.
        int currentMonth = currentDate.getMonthValue();
        int currentYear = currentDate.getYear();
        for(Journal journal: distributor.getJournals().values()){
            for(Subscription subscription:journal.getSubscriptions()){
                if(subscription.getDates().getStartYear() == currentYear && subscription.getDates().getStartMonth() <= currentMonth){ //tarihi gecmis abonelikleri gostermeyelim.
                    if(subscription.getPaymentInfo().getReceivedPayment() < subscription.getCopies() * journal.getFrequency() * (1-subscription.getPaymentInfo().getDiscountRatio())* journal.getIssuePrice()){
                        double needmoney = subscription.getCopies() * journal.getFrequency() * (1-subscription.getPaymentInfo().getDiscountRatio())* journal.getIssuePrice() - subscription.getPaymentInfo().getReceivedPayment();
                        String formatValue = String.format("%.1f", needmoney);
                        OutputArea.append("The payment made by the subscriber '"+subscription.getSubscriber().getName()+ "' for the '"+ journal.getName() +"' journal is insufficient: Need '" + formatValue + "' more\n" );
                    }
                }
                else if(subscription.getDates().getEndYear() == currentYear && subscription.getDates().getEndYear() >= currentMonth){ //tarihi gecmis abonelikleri gostermeyelim.
                    if(subscription.getPaymentInfo().getReceivedPayment() < subscription.getCopies() * journal.getFrequency() * (1-subscription.getPaymentInfo().getDiscountRatio())* journal.getIssuePrice()){
                        double needmoney = subscription.getCopies() * journal.getFrequency() * (1-subscription.getPaymentInfo().getDiscountRatio())* journal.getIssuePrice() - subscription.getPaymentInfo().getReceivedPayment();
                        String formatValue = String.format("%.2f", needmoney);
                        OutputArea.append("The payment made by the subscriber '"+subscription.getSubscriber().getName()+ "' for the '"+ journal.getName() +"' journal is insufficient: Need '" + formatValue + "' more\n");
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        OutputArea.setEditable(false);
        OutputArea.setColumns(20);
        OutputArea.setRows(5);
        jScrollPane1.setViewportView(OutputArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListIncompletePaymentsEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListIncompletePaymentsEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListIncompletePaymentsEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListIncompletePaymentsEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListIncompletePaymentsEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea OutputArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
